### ISSUE TITLE
Update DAPM to use the `push_package` API call

### ISSUE THREAD

**Issue by mferrare** [Digital-Law-Lab/Digital-Law-Lab#3]
It may not actually be called `push_package` but there is something like that in the API doco.  I should replace my `push` call with that push_package thingy.

Reason is that @jhpyle has modified the DA structure so that python modules are no longer stored in `data/modules` but either in `data` or at the top level (I forgot which).

That means my current version of DAPM will not push modules to the proper location.  Lucky we're not using that yet!!

**Comment by jhpyle** [comment]
In the Playground there is a "folder" for modules but in the Python package the .py files in a package `docassemble.mypackage` have always been placed in the `docassemble/mypackage` directory in the package contents, not under the `data` directory.

The way that Python works, if you have a module `bar.py` in the package `foo`, the directory structure is that there is a directory called `foo` at the same level as the `setup.py` file, and in the `foo` directory there is a `bar.py` file along with an empty `__init__.py` file. Thus if you reference `foo.bar`, Python knows that you are referring to the `bar.py` file in the `foo` directory. There are other ways that `__init__.py` can be used, but the empty `__init__.py` system is a standard one that is used.

In docassemble it is a little bit different because I use `docassemble` as a "namespace package," so if the docassemble add-on package is `docassemble.mypackage`, there needs to be a `docassemble` directory and then a `mypackage` directory inside of that, and the Python module files go in the `mypackage` directory.

Python packages are supposed to be for code, not data. Many packages that rely upon data have a routine that downloads the data from the internet at runtime when the package is first used and stores it somewhere on the file system. (This causes problems for machines not connected to the internet.) I chose to bundle data files (interview YAML files, DOCX template files, etc.) inside the Python packages themselves. So anything that is not code goes into the `data` directory, which is at the same level as the .py files. I use the `pkg_resources` package to access files in the package. There are different types of data that go with a docassemble package, so there are subdirectories under `data`.

Anyway, since Python modules are code, not data, they don't belong in the `data` directory.

**Comment by mferrare** [comment]
@jhpyle you da man!! I had put your name in here out of habit and laziness.  Was not expecting you to reply but many thanks for the reply regardless!!

**Comment by mferrare** [comment]
@jhpyle, the `api/playground` endpoint can be passed a `folder` key which can include `modules`.  If I use this endpoint and call only the `modules` folder, does it push up `*.py` files in `docassemble/packagename` or the contents of `docassemble/packagename/data/modules`?  Or something else?

**Comment by mferrare** [comment]
Docassemble package structure is as follows:

- questions, templates, static, sources are all in `docassemble/packagesname/data/*folder_name*`
- modules are in `docassemble/packagename` and (presumably) are called *.py

That means we need to do this to build up the structure

- get the path like we do in `get_path_to_folders()`
- but for modules, just get `docassemble/packagename`
- if we were good we'd account for the entire folder structure in docassemble/packagename
  - but exclude data/
  - and exclude __init.py__
- or we could account for every *.py file in docassemble/packagename and subfolders
   - ^^^ I think this might be the better approach

So, we can't just get the path to the folders, path will be different depending on whether we're in modules or not.  And if we're in modules are we recursing?

So, maybe what we need to do is return a dictionary like this:
```JSON
    {
        questions : path to questions
        static    : path to static
        templates : path to templates
        sources   : path to sources
        modules   : (different) path to modules
    }
```

**Comment by mferrare** [comment]
UPDATE:

I created a test package and uploaded it and downloaded it to/from docassemble.  

1. I had a module in a subdir (`test2.py`).  When I upload, the module in the subdir is uploaded to the `modules` 'folder' in the Playground.  When I download the package, test2.py appears at the 'top level' (ie: where all the other modules are
2. I created a module called `test3` (ie: no `.py`).  It doesn't upload/download.

So, we can assume:

1. no nesting/subdirs
2. all modules end in `.py`

**Comment by mferrare** [comment]
[] Make sure `list_files_to_push_or_pull()` works

**Comment by mferrare** [comment]
Pushing now works fine.  Pushing a single module file also works fine.

I should implement pulling one day but I hardly use it so not for now.

**Comment by mferrare** [comment]
In the end I'm not using `push_package` API call. Instead I just modified the code to account for modules being where they should be instead of in `data/modules` (which is where I had assumed them to be previously).  Pushing works fine.  Pulling still doesn't.

I'm going to close this ticket.  If I ever need pull I'll open another ticket.
